project_id = "rlxhgffmspfstwlxljdc"

[functions.admin-create-user]
verify_jwt = false

[functions.ocr-odometer]
verify_jwt = false

[functions.run-jobs]
verify_jwt = false

[functions.maintenance-reminders]
verify_jwt = false
